services:
  - type: web
    name: lexcom-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "./render-build.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lexcom-db
          property: connectionString
