services:
  - type: web
    name: lexcom-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lexcom-db
          property: connectionString
